<a href="https://colab.research.google.com/github/Ssurf777/DL_from_scratch/blob/main/Deep_Learning_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Deep Learning from scratch

# 多次元配列

In [ ]:
import numpy as np
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


配列次元数の取得 np.ndim()

In [ ]:
print(f'{np.ndim(A)}次元')

1次元


In [ ]:
print(A.shape)

(4,)


In [ ]:
print(A.shape[0])

4


In [ ]:
B = np.array([ [1,2],[3,4],[5,6] ])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
np.ndim(B)

2

In [ ]:
B.shape

(3, 2)

$$
\begin{pmatrix}1 & 2 \\3 & 4\end{pmatrix}
\begin{pmatrix}5 & 6 \\7 & 8\end{pmatrix}
=\begin{pmatrix} 19 & 22 \\ 43 & 50 \end{pmatrix}
$$

In [ ]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]


$$
\begin{pmatrix}1 & 2 & 3\\4 & 5 & 6\end{pmatrix}
\begin{pmatrix}1 & 2 \\3 & 4\\5 & 6\end{pmatrix}
=\begin{pmatrix} 22 & 28 \\ 49 & 64 \end{pmatrix}
$$

In [ ]:
A = np.array([[1,2,3], [4,5,6]])
print(A.shape)

B = np.array([[1, 2], [3, 4], [5, 6]])
print(B.shape)

print("※2行3列×3行2列であると2行2列になる")

(2, 3)
(3, 2)
※2行3列×3行2列であると2行2列になる


In [ ]:
C = np.dot(A, B)
print(C)

[[22 28]
 [49 64]]


$$
\begin{pmatrix}1 & 2 \\3 & 4 \\ 5 & 6\end{pmatrix}
\begin{pmatrix}7 & 8\end{pmatrix}
=\begin{pmatrix} 23 & 53 & 83 \end{pmatrix}
$$

In [ ]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([7,8])
C = np.dot(A, B)
print(C)

[23 53 83]


# ニューラルネットワークの実装

In [ ]:
import numpy as np

# Neural Network INPUT
X = np.array([1,2])
print(f'X.shape:{X.shape}')

# Weight
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)
print(f'W.shape:{W.shape}')

X.shape:(2,)
[[1 3 5]
 [2 4 6]]
W.shape:(2, 3)


In [ ]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]


## 各層における信号伝達の実装

$$
A^{(1)} = \begin{pmatrix}
a^{(1)}_1 & a^{(1)}_2 & a^{(1)}_3
\end{pmatrix}
$$

$$
X=\begin{pmatrix}
x_1&x_2
\end{pmatrix}
$$

$$
B^{(1)} = \begin{pmatrix}
b^{(1)}_1 & b^{(1)}_2 & b^{(1)}_3
\end{pmatrix}
$$

$$
W^{(1)} = \begin{pmatrix}
w^{(1)}_{11} & w^{(1)}_{12} & w^{(1)}_{13} \\
w^{(1)}_{21} & w^{(1)}_{22} & w^{(1)}_{23}
\end{pmatrix}
$$



$$
w^{(1)}_{12}
$$
重みの()内は1層目の重みを指し
下付き12は前層2番目のニューロンから次層1番目のニューロンを結ぶエッジの重み

In [6]:
  import numpy as np

  # INPUT 1x2
  X = np.array([1.0, 0.5])

  # Weight of hidden layer1 2x3
  W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])

  # baias 1x3
  B1 = np.array([0.1, 0.2, 0.3])

  print(W1.shape)
  print(X.shape)
  print(B1.shape)

# OUTPUT 1x3
  A1 =  np.dot(X, W1) + B1
  print(A1)

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]


$$
sigmoid(x)=\frac{1}{(1 +\exp{(-x)})}
$$

In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [8]:
# Activation Sigmoid
Z1 = sigmoid(A1)
print(f'A:{A1}')
print(f'Z:{Z1}')

A:[0.3 0.7 1.1]
Z:[0.57444252 0.66818777 0.75026011]


In [9]:
# Weight of hidden layer2 (3x2)
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])

# bias2
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)


(3,)
(3, 2)
(2,)


In [10]:
#  2層目の出力
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

### 恒等関数の定義

In [14]:
# 最終層の恒等関数
# 最終層は回帰の場合->恒等関数, 2値分類の場合->シグモイド, 多クラス分類の場合->softmax
def identity_function(x):
    return x

In [15]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)

In [16]:
print(Y)

[0.31682708 0.69627909]


In [17]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4],[0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3],[0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])

    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]


### Softmax関数の定義

In [18]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

### Softmax関数の実装上の注意

In [22]:
a = np.array([1010, 1000, 990])
print(np.exp(a) / np.sum(np.exp(a)))
# expは容易に大きい値となるため、nanとなりやすい

[nan nan nan]


<ipython-input-22-71b6d1da37bf>:2: RuntimeWarning: overflow encountered in exp
  print(np.exp(a) / np.sum(np.exp(a)))
<ipython-input-22-71b6d1da37bf>:2: RuntimeWarning: invalid value encountered in divide
  print(np.exp(a) / np.sum(np.exp(a)))


### Softmaxのオーバーフロー対策

$$
y_k = \frac{\exp(a_k)}{\sum \exp(a_i)}
=\frac{C\exp(a_k)}{C\Sigma\exp(a_i)}
=\frac{\exp(a_k + \log{C})} {\Sigma \exp{(a_i + \log{C})}}
$$

In [23]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) # prevent overflow
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [24]:
softmax(a = np.array([1010, 1000, 990]))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])